/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlybanhangggggg;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hiep nguyen
 */
public class BanHangView extends javax.swing.JFrame {

    /**
     * Creates new form BanHangView
     */
    DefaultTableModel defau;
    QuanLySanPham qlsp = new QuanLySanPham();
    QuanLyGioHang qlgh = new QuanLyGioHang();
    QuanLyHoaDon qlhd = new QuanLyHoaDon();
    QuanLyKhuyenMai qlkm = new QuanLyKhuyenMai();

    public BanHangView() {
        initComponents();
        jPanel5.setVisible(true);
        jPanel6.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        lb1.setForeground(Color.red);
        rdTatCa.setSelected(true);
        loadBangSanPham();
        loadGioHang();
        loadHoaDon();
        loadBangQLSP();
        loadHoaDonChiTiet();
        loadBangKhuyeMai();

    }

    void loadBangQLSP() {
        defau = (DefaultTableModel) tblQLSP.getModel();
        defau.setRowCount(0);
        for (SanPham sp : qlsp.getAll()) {
            defau.addRow(new Object[]{
                sp.getMa(), sp.getTen(), sp.getTheLoai(), sp.getChatLieu(), sp.getSize(), sp.getSoLuong(), sp.getDonGia()
            });
        }
    }

    void loadBangKhuyeMai() {
        defau = (DefaultTableModel) tblBangKhuyenMai.getModel();
        defau.setRowCount(0);
        int stt = 0;
        for (KhuyenMai km : qlkm.getAllKM()) {
            stt++;
            defau.addRow(new Object[]{
                stt, km.getMa(), km.getTen(), km.getNgayBD(), km.getNgayKT(), km.getDieuKien(), km.getSoLuong(), km.getVaiTro(), km.getGiam()
            });
        }
    }

    void loadHoaDon() {
        defau = (DefaultTableModel) tblHoaDon.getModel();
        defau.setRowCount(0);
        int stt = 0;
        for (HoaDon hd : qlhd.getHD()) {
            if (hd.getTrangThai().equals("Cho thanh toan")) {
                stt++;
                defau.addRow(new Object[]{
                    stt, hd.getMaHD(), hd.getTenNV(), hd.getNgay(), hd.getTrangThai()
                });
            }
        }
    }

    void loadHoaDonChiTiet() {
        defau = (DefaultTableModel) tblBangoHDCT.getModel();
        defau.setRowCount(0);
        int stt = 0;
        for (HoaDon hd : qlhd.getHD()) {
            if (hd.getTrangThai().equals("Da thanh toan") || hd.getTrangThai().equals("Huy hoa don")) {
                stt++;
                defau.addRow(new Object[]{
                    stt, hd.getMaHD(), hd.getTenNV(), hd.getNgay(), hd.getTrangThai()
                });
            }
        }
    }

    void loadGioHang() {
        defau = (DefaultTableModel) tblGioHang.getModel();
        defau.setRowCount(0);
        String maHD = txtMa.getText();
        int stt = 0;
        for (GioHang gh : qlgh.getGioHang(maHD)) {
            stt++;
            defau.addRow(new Object[]{
                stt, gh.getMa(), gh.getTen(), gh.getSoLuong(), gh.getDonGia(), gh.thanhTien()
            });
        }
    }

    void loadGioHangoChiTiet() {
        defau = (DefaultTableModel) tblBangGioHangoHDCT.getModel();
        defau.setRowCount(0);
        String maHD = txtMa.getText();
        int stt = 0;
        for (GioHang gh : qlgh.getGioHang(maHD)) {
            stt++;
            defau.addRow(new Object[]{
                stt, gh.getMa(), gh.getTen(), gh.getSoLuong(), gh.getDonGia(), gh.thanhTien()
            });
        }
    }

    void loadBangSanPham() {
        defau = (DefaultTableModel) tblSanPham.getModel();
        defau.setRowCount(0);
        for (SanPham sp : qlsp.getAll()) {
            defau.addRow(new Object[]{
                sp.getMa(), sp.getTen(), sp.getTheLoai(), sp.getChatLieu(), sp.getSize(), sp.getSoLuong(), sp.getDonGia()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btTaoHoaDon = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        btXoa = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        btTimKiem = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTienKhach = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTienThua = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtTongTien = new javax.swing.JTextField();
        txtNgay = new javax.swing.JTextField();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtKMBanHang = new javax.swing.JTextField();
        btApDung = new javax.swing.JButton();
        btHuyHoaDon = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBangKhuyenMai = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtTenKM = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtNgayBD = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtNgayKT = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtDKKM = new javax.swing.JTextField();
        txtSoLuongKM = new javax.swing.JTextField();
        txtVaiTroKM = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtGiam = new javax.swing.JTextField();
        btThemKM = new javax.swing.JButton();
        btXoaKM = new javax.swing.JButton();
        btTimKiemKM = new javax.swing.JButton();
        txtTimKiemKM = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblQLSP = new javax.swing.JTable();
        bthem = new javax.swing.JButton();
        btttXoa = new javax.swing.JButton();
        btCapNhat = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btttTimSP = new javax.swing.JButton();
        txtTK = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Ma = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Ten = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cboTheLoai = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        ChatLieu = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cboSize = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        soLuong = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        DonGia = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblBangGioHangoHDCT = new javax.swing.JTable();
        txtTimKiemHDCT = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rdDa = new javax.swing.JRadioButton();
        rdHuy = new javax.swing.JRadioButton();
        rdTatCa = new javax.swing.JRadioButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblBangoHDCT = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb1.setText("  Bán Hàng");
        lb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb1MouseClicked(evt);
            }
        });

        lb2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb2.setText("  Khuyến Mãi");
        lb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb2MouseClicked(evt);
            }
        });

        lb3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb3.setText("  Quản Lý SP");
        lb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb3MouseClicked(evt);
            }
        });

        lb4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb4.setText("Hóa Đơn Chi Tiết");
        lb4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lb4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 620));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btTaoHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btTaoHoaDon.setText("Tạo Hóa Đơn");
        btTaoHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btTaoHoaDonMouseClicked(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Quản lý hóa đơn"));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã HĐ", "Tên NV", "Ngày Tạo", "Trạng Thái"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Giỏ hàng"));

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Số Lượng", "Đơn Giá", "Thành Tiền"
            }
        ));
        tblGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGioHangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblGioHang);

        btXoa.setText("Xóa");
        btXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btXoaMouseClicked(evt);
            }
        });
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        btXoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btXoaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btXoa)
                .addGap(29, 29, 29))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Sản Phẩm"));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Thể Loại", "Chất Liệu", "Size", "Số Lượng", "Đơn Giá"
            }
        ));
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblSanPham);

        btTimKiem.setText("Tìm Kiếm");
        btTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btTimKiemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btTimKiem)
                .addGap(36, 36, 36))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btTimKiem)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Tạo hóa đơn"));

        jLabel4.setText("Tên NV");

        jLabel5.setText("Mã HĐ");

        jLabel6.setText("Ngày Tạo");

        jLabel7.setText("Tổng Tiền");

        jLabel8.setText("Phương Thức TT");

        jLabel9.setText("Tiền Khách Đưa");

        txtTienKhach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienKhachKeyReleased(evt);
            }
        });

        jLabel10.setText("Tiền Thừa");

        txtTienThua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienThuaKeyReleased(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền Mặt", "Chuyển Khoản" }));

        jButton3.setText("Thanh Toán");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel3.setText("Mã Khuyến Mại");

        btApDung.setText("Áp Dụng");
        btApDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btApDungMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTienKhach, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, 0, 238, Short.MAX_VALUE)
                            .addComponent(txtTienThua)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgay)
                            .addComponent(txtTen)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(txtKMBanHang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btApDung)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(127, 127, 127))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKMBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btApDung))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTienKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(24, 24, 24))
        );

        btHuyHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btHuyHoaDon.setText("Hủy Hóa Đơn");
        btHuyHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btHuyHoaDonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btHuyHoaDon)
                            .addComponent(btTaoHoaDon))
                        .addGap(130, 130, 130))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btTaoHoaDon)
                        .addGap(18, 18, 18)
                        .addComponent(btHuyHoaDon)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 1090, 620));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setPreferredSize(new java.awt.Dimension(1090, 617));

        tblBangKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã KM", "Tên KM", "Ngày Bắt đầu", "Ngày Kết Thúc", "Điều Kiện", "Số Lượng ", "Mô Tả", "Giảm %"
            }
        ));
        tblBangKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangKhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBangKhuyenMai);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 51, 0));
        jLabel19.setText("Mã Khuyến Mại");

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel20.setText("Mã KM");

        jLabel21.setText("Tên KM");

        jLabel22.setText("Ngày Bắt Đầu");

        jLabel23.setText("Ngày Kết Thúc");

        jLabel24.setText("Điều Kiện");

        jLabel25.setText("Số Lượng");

        jLabel26.setText("Mô Tả");

        jLabel27.setText("Giảm %");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaKM)
                    .addComponent(txtNgayBD)
                    .addComponent(txtTenKM)
                    .addComponent(txtNgayKT, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addGap(218, 218, 218)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDKKM)
                    .addComponent(txtSoLuongKM)
                    .addComponent(txtVaiTroKM, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(txtGiam))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(txtDKKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtTenKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txtSoLuongKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txtVaiTroKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        btThemKM.setText("Thêm");
        btThemKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btThemKMMouseClicked(evt);
            }
        });

        btXoaKM.setText("Xóa");
        btXoaKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btXoaKMMouseClicked(evt);
            }
        });

        btTimKiemKM.setText("Tìm Kiếm");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jLabel19))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(btThemKM)
                        .addGap(46, 46, 46)
                        .addComponent(btXoaKM)
                        .addGap(217, 217, 217)
                        .addComponent(btTimKiemKM)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiemKM, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThemKM)
                    .addComponent(btXoaKM)
                    .addComponent(btTimKiemKM)
                    .addComponent(txtTimKiemKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 1019, 617));

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setPreferredSize(new java.awt.Dimension(1090, 617));

        tblQLSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Thể Loại", "Chất Liệu", "Size", "Số Lượng", "Đơn Giá"
            }
        ));
        tblQLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLSPMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblQLSP);

        bthem.setText("Thêm");
        bthem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bthemMouseClicked(evt);
            }
        });
        bthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthemActionPerformed(evt);
            }
        });

        btttXoa.setText("Xóa");
        btttXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btttXoaMouseClicked(evt);
            }
        });

        btCapNhat.setText("Cập Nhật");
        btCapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCapNhatMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 102));
        jLabel12.setText("QUẢN LÝ SẢN PHẨM");

        btttTimSP.setText("Tìm Kiếm");
        btttTimSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btttTimSPMouseClicked(evt);
            }
        });

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Mã");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Tên");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Thể Loại");

        cboTheLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ao", "Quan" }));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Chất Liệu");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Size");

        cboSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L", "XL", "XXL", "XXXL" }));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Số Lượng");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Đơn Giá");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(cboTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(Ten, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(Ma, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(262, 262, 262)
                                .addComponent(jLabel15)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cboTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(ChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(jLabel12))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(bthem)
                        .addGap(50, 50, 50)
                        .addComponent(btttXoa)
                        .addGap(53, 53, 53)
                        .addComponent(btCapNhat)
                        .addGap(179, 179, 179)
                        .addComponent(btttTimSP)
                        .addGap(18, 18, 18)
                        .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(297, 297, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addGap(24, 24, 24)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btttTimSP)
                    .addComponent(btCapNhat)
                    .addComponent(btttXoa)
                    .addComponent(bthem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 1090, 617));

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setPreferredSize(new java.awt.Dimension(1090, 617));

        tblBangGioHangoHDCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Số Lượng", "Đơn Giá", "Thành Tiền"
            }
        ));
        jScrollPane6.setViewportView(tblBangGioHangoHDCT);

        jButton8.setText("Tìm kiếm");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 153));
        jLabel1.setText("HÓA ĐƠN CHI TIẾT");

        buttonGroup1.add(rdDa);
        rdDa.setText("Đã thanh toán");
        rdDa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdDaMouseClicked(evt);
            }
        });
        rdDa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdHuy);
        rdHuy.setText("Đã hủy");
        rdHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdHuyMouseClicked(evt);
            }
        });
        rdHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdHuyActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdTatCa);
        rdTatCa.setText("Tất cả");
        rdTatCa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdTatCaMouseClicked(evt);
            }
        });

        tblBangoHDCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã HĐ", "Tên NV", "Ngày Tạo", "Trạng Thái"
            }
        ));
        tblBangoHDCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangoHDCTMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblBangoHDCT);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(txtTimKiemHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8)
                                .addGap(101, 101, 101)
                                .addComponent(rdDa)
                                .addGap(18, 18, 18)
                                .addComponent(rdHuy)
                                .addGap(18, 18, 18)
                                .addComponent(rdTatCa))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel1)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiemHDCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8)
                    .addComponent(rdDa)
                    .addComponent(rdHuy)
                    .addComponent(rdTatCa))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 1090, 617));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1246, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb1MouseClicked
        // TODO add your handling code here:
        jPanel5.setVisible(true);
        jPanel6.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        lb3.setForeground(Color.BLACK);
        lb2.setForeground(Color.BLACK);
        lb1.setForeground(Color.red);
        lb4.setForeground(Color.BLACK);
    }//GEN-LAST:event_lb1MouseClicked

    private void lb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb2MouseClicked
        // TODO add your handling code here:
        jPanel5.setVisible(false);
        jPanel6.setVisible(true);
        jPanel9.setVisible(false);
        jPanel10.setVisible(false);
        lb3.setForeground(Color.BLACK);
        lb1.setForeground(Color.BLACK);
        lb2.setForeground(Color.red);
        lb4.setForeground(Color.BLACK);
    }//GEN-LAST:event_lb2MouseClicked

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        // TODO add your handling code here:

        for (HoaDon h : qlhd.getHD()) {
            if (txtMa.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn hóa đơn");
                return;
            }
        }
        int i = tblSanPham.getSelectedRow();
        String ma = (String) tblSanPham.getValueAt(i, 0);
        String a = JOptionPane.showInputDialog("Vui lòng điền số lượng");
        if (a == null) {
            return;
        }
        int sl = (int) tblSanPham.getValueAt(i, 5);
        if (Integer.parseInt(a) > sl) {
            JOptionPane.showMessageDialog(this, "Nhập lại số lượng");
            return;
        }
        if (Integer.parseInt(a) <= 0) {
            JOptionPane.showMessageDialog(this, "Nhập lại số lượng");
            return;
        }
        Boolean Check1 = qlsp.truSP(Integer.parseInt(a), ma);
        if (Check1) {
            JOptionPane.showMessageDialog(this, "Thành công");
            loadBangSanPham();
        }

        String ten = (String) tblSanPham.getValueAt(i, 1);
        int donGia = (int) tblSanPham.getValueAt(i, 6);
        GioHang gh = new GioHang(ma, ten, Integer.parseInt(a), donGia);
        String maHD = txtMa.getText();
        for (GioHang gioHang : qlgh.getGioHang(maHD)) {
            if (ma.equals(gioHang.getMa())) {
                Boolean nhanDoi = qlsp.nhanDoiSPtrogMa(Integer.parseInt(a), ma);
                loadGioHang();
                return;
            }
        }
        Boolean check = qlgh.themGioHang(gh, maHD);
        loadGioHang();

        int tong = 0;
        for (GioHang gioHang : qlgh.getGioHang(maHD)) {
            tong += gioHang.thanhTien();
        }
        txtTongTien.setText(tong + "");
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void btTaoHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTaoHoaDonMouseClicked
        // TODO add your handling code here:
        int stt = qlhd.getHD().size() + 1;
        String MaHD = "HD" + stt;
        txtMa.setText(MaHD);
        String ten = "Nguyen Van C";
        txtTen.setText(ten);
        String ngay = "2023-01-27";
        txtNgay.setText(ngay);
        String trangThai = "Cho thanh toan";
        HoaDon hdd = new HoaDon(MaHD, ten, ngay, trangThai);
        Boolean check = qlhd.taHD(hdd);
        if (check) {
            JOptionPane.showMessageDialog(this, "Tạo thành công");
            loadHoaDon();
        } else {
            JOptionPane.showMessageDialog(this, "Tạo Thất bại");

        }
        txtTongTien.setText("");
    }//GEN-LAST:event_btTaoHoaDonMouseClicked
    public void LoadHDCT() {
        int i = tblHoaDon.getSelectedRow();
        String ma = (String) tblHoaDon.getValueAt(i, 1);
        txtMa.setText(ma);
        String ten = (String) tblHoaDon.getValueAt(i, 2);
        txtTen.setText(ten);
        String ngay = (String) tblHoaDon.getValueAt(i, 3);
        txtNgay.setText(ngay);
    }

    public void loadhdct2() {
        ArrayList<GioHang> litGH = new ArrayList<>();
        String maHD = txtMa.getText();
        loadGioHang();
    }
    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        LoadHDCT();
        loadhdct2();
        String ma = txtMa.getText();
        int tong = 0;
        for (GioHang gioHang : qlgh.getGioHang(ma)) {
            tong += gioHang.thanhTien();
        }
        txtTongTien.setText(tong + "");
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btXoaActionPerformed

    private void btXoaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btXoaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btXoaKeyPressed

    private void btXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btXoaMouseClicked
        // TODO add your handling code here:
        int i = tblGioHang.getSelectedRow();
        String ma = (String) tblGioHang.getValueAt(i, 1);
        int soLuong = (int) tblGioHang.getValueAt(i, 3);
        Boolean check = qlsp.congSP(soLuong, ma);
        if (check) {
            JOptionPane.showMessageDialog(this, "Thành công");
            loadBangSanPham();
        }

        qlgh.xoa(ma);
        int tong = 0;
        for (GioHang gioHang : qlgh.getGioHang(txtMa.getText())) {
            tong += gioHang.thanhTien();
        }
        loadGioHang();
    }//GEN-LAST:event_btXoaMouseClicked

    private void btTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btTimKiemMouseClicked
        // TODO add your handling code here:
        String timKiem = txtTimKiem.getText();
        defau = (DefaultTableModel) tblSanPham.getModel();
        defau.setRowCount(0);
        for (SanPham sp : qlsp.search(timKiem)) {
            defau.addRow(new Object[]{
                sp.getMa(), sp.getTen(), sp.getTheLoai(), sp.getChatLieu(), sp.getSize(), sp.getSoLuong(), sp.getDonGia()
            });
        }
    }//GEN-LAST:event_btTimKiemMouseClicked

    private void txtTienThuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienThuaKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTienThuaKeyReleased

    private void txtTienKhachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachKeyReleased
        // TODO add your handling code here:
        if (!txtTienKhach.getText().matches("^\\d+$")) {
            JOptionPane.showMessageDialog(this, "Tiền không được điền chữ");
            return;
        }
        int hieu = Integer.parseInt(txtTienKhach.getText()) - Integer.parseInt(txtTongTien.getText());
        txtTienThua.setText(hieu + "");
    }//GEN-LAST:event_txtTienKhachKeyReleased

    private void bthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bthemActionPerformed

    private void lb3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb3MouseClicked
        // TODO add your handling code here:
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel9.setVisible(true);
        jPanel10.setVisible(false);
        lb2.setForeground(Color.BLACK);
        lb1.setForeground(Color.BLACK);
        lb3.setForeground(Color.red);
        lb4.setForeground(Color.BLACK);

    }//GEN-LAST:event_lb3MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String tt = txtTienKhach.getText();
        String ttt = txtTongTien.getText();

        if (Integer.parseInt(tt) >= Integer.parseInt(ttt)) {
            Boolean check = qlhd.tt(txtMa.getText());
            if (check) {
                JOptionPane.showMessageDialog(this, "Thanh toán thành công");
                loadHoaDon();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Thanh toán thất bại");
            return;
        }
        loadHoaDonChiTiet();
    }//GEN-LAST:event_jButton3MouseClicked

    SanPham getForm() {
        SanPham sp = new SanPham();
        sp.setMa(Ma.getText());
        sp.setTen(Ten.getText());
        sp.setTheLoai((String) cboTheLoai.getSelectedItem());
        sp.setChatLieu(ChatLieu.getText());
        sp.setSize(cboSize.getSelectedItem().toString());
        sp.setSoLuong(Integer.parseInt(soLuong.getText()));
        sp.setDonGia(Integer.parseInt(DonGia.getText()));
        return sp;
    }

    void setForm(SanPham s) {
        Ma.setText(s.getMa());
        Ten.setText(s.getTen());
        cboTheLoai.setSelectedItem(s.getTheLoai());
        ChatLieu.setText(s.getChatLieu());
        cboSize.setSelectedItem(s.getSize());
        soLuong.setText(s.getSoLuong() + "");
        DonGia.setText(s.getDonGia() + "");

    }

    KhuyenMai getFormKM() {
        KhuyenMai km = new KhuyenMai();
        km.setMa(txtMaKM.getText());
        km.setTen(txtTenKM.getText());
        km.setNgayBD(txtNgayBD.getText());
        km.setNgayKT(txtNgayKT.getText());
        km.setDieuKien(txtDKKM.getText());
        km.setSoLuong(Integer.parseInt(txtSoLuongKM.getText()));
        km.setVaiTro(txtVaiTroKM.getText());
        km.setGiam(Integer.parseInt(txtGiam.getText()));
        return km;
    }

    void setFormKhuyenMai(KhuyenMai km) {
        txtMaKM.setText(km.getMa());
        txtTenKM.setText(km.getTen());
        txtNgayBD.setText(km.getNgayBD());
        txtNgayKT.setText(km.getNgayKT());
        txtDKKM.setText(km.getDieuKien());
        txtSoLuongKM.setText(km.getSoLuong() + "");
        txtVaiTroKM.setText(km.getVaiTro());
        txtGiam.setText(km.getGiam() + "");
    }

    int checkKhuyenMai() {
        for (KhuyenMai km : qlkm.getAllKM()) {
            if (txtMaKM.getText().equals(km.getMa())) {
                JOptionPane.showMessageDialog(this, "Mã không được trùng");
                return 1;
            }
        }
        if (txtMaKM.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mã không được trống");
            return 1;
        }
        if (txtTenKM.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Tên không được trống");
            return 1;
        }
        if (txtNgayBD.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ngày không được trống");
            return 1;
        }
        if (txtNgayKT.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ngày không được trống");
            return 1;
        }
        if (txtDKKM.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Điều kiện không được trống");
            return 1;
        }
        if (txtSoLuongKM.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Số lượng không được trống");
            return 1;
        }
        if (txtVaiTroKM.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vai trò không được trống");
            return 1;
        }
        if (txtGiam.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Điền % giảm giá");
            return 1;
        }
        return 0;
    }

    int check() {
        for (SanPham s : qlsp.getAll()) {
            if (Ma.getText().equals(s.getMa())) {
                JOptionPane.showMessageDialog(this, "Mã không được trùng");
                return 1;
            }
        }
        if (Ma.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mã không được trống");
            return 1;
        }
        if (Ten.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Tên không được trống");
            return 1;
        }
        if (ChatLieu.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chất liệu không được trống");
            return 1;
        }
        if (soLuong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Số lượng không được trống");
            return 1;
        }
        if (DonGia.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Đơn giá không được trống");
            return 1;
        }
        return 0;
    }

    int checkCN(String ma) {
        if (!ma.equals(Ma.getText())) {
            JOptionPane.showMessageDialog(this, "Không được sửa mã");
            return 1;
        }
        if (Ten.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Tên không được trống");
            return 1;
        }
        if (ChatLieu.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chất liệu không được trống");
            return 1;
        }
        if (soLuong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Số lượng không được trống");
            return 1;
        }
        if (DonGia.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Đơn giá không được trống");
            return 1;
        }
        return 0;
    }

    private void tblQLSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLSPMouseClicked
        // TODO add your handling code here:
        ArrayList<SanPham> l = qlsp.getAll();
        int i = tblQLSP.getSelectedRow();
        setForm(l.get(i));

    }//GEN-LAST:event_tblQLSPMouseClicked

    private void bthemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bthemMouseClicked
        // TODO add your handling code here:
        if (check() == 1) {
            return;
        }
        qlsp.ThemSP(getForm());
        JOptionPane.showMessageDialog(this, "Thêm thành công");
        loadBangQLSP();
        loadBangSanPham();
    }//GEN-LAST:event_bthemMouseClicked

    private void lb4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb4MouseClicked
        // TODO add your handling code here:
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel9.setVisible(false);
        jPanel10.setVisible(true);
        lb3.setForeground(Color.BLACK);
        lb1.setForeground(Color.BLACK);
        lb4.setForeground(Color.red);
        lb2.setForeground(Color.black);
    }//GEN-LAST:event_lb4MouseClicked

    private void rdHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdHuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdHuyActionPerformed

    private void btttXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btttXoaMouseClicked
        // TODO add your handling code here:
        int i = tblQLSP.getSelectedRow();
        String ma = Ma.getText();
        Boolean xoa = qlsp.xoaSP(ma);
        if (xoa) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
        }
        loadBangQLSP();
        loadBangSanPham();
    }//GEN-LAST:event_btttXoaMouseClicked

    private void btCapNhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCapNhatMouseClicked
        // TODO add your handling code here:
        int i = tblQLSP.getSelectedRow();
        if (checkCN(tblQLSP.getValueAt(i, 0).toString()) == 1) {
            return;
        }
        String ma = (String) tblQLSP.getValueAt(i, 0);
        Boolean capNhat = qlsp.caphat(getForm(), ma);
        if (capNhat) {
            JOptionPane.showMessageDialog(this, "Cập nhật thanh công");
        }
        loadBangSanPham();
        loadBangQLSP();

    }//GEN-LAST:event_btCapNhatMouseClicked

    private void btttTimSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btttTimSPMouseClicked
        // TODO add your handling code here:
        String tkk = txtTK.getText();
        defau = (DefaultTableModel) tblQLSP.getModel();
        defau.setRowCount(0);
        for (SanPham sp : qlsp.tk(tkk)) {
            defau.addRow(new Object[]{
                sp.getMa(), sp.getTen(), sp.getTheLoai(), sp.getChatLieu(), sp.getSize(), sp.getSoLuong(), sp.getDonGia()
            });
        }
    }//GEN-LAST:event_btttTimSPMouseClicked

    private void rdDaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rdDaActionPerformed

    private void tblBangoHDCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangoHDCTMouseClicked
        // TODO add your handling code here:
        int i = tblBangoHDCT.getSelectedRow();
        String ma = (String) tblBangoHDCT.getValueAt(i, 1);
        txtMa.setText(ma);
        String ten = (String) tblBangoHDCT.getValueAt(i, 2);
        txtTen.setText(ten);
        String ngay = (String) tblBangoHDCT.getValueAt(i, 3);
        txtNgay.setText(ngay);

        ArrayList<GioHang> litGH = new ArrayList<>();
        String maHD = txtMa.getText();
        loadGioHangoChiTiet();
    }//GEN-LAST:event_tblBangoHDCTMouseClicked

    private void btHuyHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btHuyHoaDonMouseClicked
        // TODO add your handling code here:    
        String ma = txtMa.getText();
        Boolean c = qlhd.HuyHD(ma);
        if (tblGioHang.getRowCount() > 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng trả lại sản phẩm");
            return;
        }
        if (c) {
            JOptionPane.showMessageDialog(this, "Hủy thành công");
            loadHoaDon();
            loadHoaDonChiTiet();
        }
    }//GEN-LAST:event_btHuyHoaDonMouseClicked

    private void rdDaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdDaMouseClicked
        // TODO add your handling code here:

        defau = (DefaultTableModel) tblBangoHDCT.getModel();
        defau.setRowCount(0);
        int stt = 0;
        for (HoaDon h : qlhd.getHD()) {
            if (h.getTrangThai().equals("Da thanh toan")) {
                stt++;
                defau.addRow(new Object[]{
                    stt, h.getMaHD(), h.getTenNV(), h.getNgay(), h.getTrangThai()
                });
            }
        }

    }//GEN-LAST:event_rdDaMouseClicked

    private void rdHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdHuyMouseClicked
        // TODO add your handling code here:
        defau = (DefaultTableModel) tblBangoHDCT.getModel();
        defau.setRowCount(0);
        int stt = 0;
        for (HoaDon h : qlhd.getHD()) {
            if (h.getTrangThai().equals("Huy hoa don")) {
                stt++;
                defau.addRow(new Object[]{
                    stt, h.getMaHD(), h.getTenNV(), h.getNgay(), h.getTrangThai()
                });
            }
        }

    }//GEN-LAST:event_rdHuyMouseClicked

    private void rdTatCaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdTatCaMouseClicked
        // TODO add your handling code here:
        defau = (DefaultTableModel) tblBangoHDCT.getModel();
        defau.setRowCount(0);
        int stt = 0;
        for (HoaDon h : qlhd.getHD()) {
            if (h.getTrangThai().equals("Da thanh toan") || h.getTrangThai().equals("Huy hoa don")) {
                stt++;
                defau.addRow(new Object[]{
                    stt, h.getMaHD(), h.getTenNV(), h.getNgay(), h.getTrangThai()
                });
            }
        }
    }//GEN-LAST:event_rdTatCaMouseClicked

    private void btThemKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btThemKMMouseClicked
        // TODO add your handling code here:

        if (checkKhuyenMai() == 1) {
            return;
        }
        Boolean themKm = qlkm.them(getFormKM());
        if (themKm) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            loadBangKhuyeMai();
        }
    }//GEN-LAST:event_btThemKMMouseClicked

    private void btApDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btApDungMouseClicked
        // TODO add your handling code here:
        for (KhuyenMai khuyenMai : qlkm.getAllKM()) {
            if (txtKMBanHang.getText().equals(khuyenMai.getMa())) {
                if (Integer.parseInt(txtTongTien.getText()) <= Integer.parseInt(khuyenMai.getDieuKien())) {
                    JOptionPane.showMessageDialog(this, "Không được áp dụng mã");
                    return;
                }
            }
//            JOptionPane.showMessageDialog(this, "Được áp dụng mã");
        }
        for (KhuyenMai km : qlkm.getAllKM()) {
            if (txtKMBanHang.getText().equals(km.getMa())) {
                txtTongTien.setText(Integer.parseInt(txtTongTien.getText()) - Integer.parseInt(txtTongTien.getText()) * km.getGiam() / 100 + "");
                JOptionPane.showMessageDialog(this, "Áp dụng thành công");

                String ma = txtKMBanHang.getText();
                qlkm.truSoLuongKhuyenMai(ma);
                loadBangKhuyeMai();

                return;
            }
        }
        JOptionPane.showMessageDialog(this, "áp dụng thất bại");


    }//GEN-LAST:event_btApDungMouseClicked

    private void tblBangKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangKhuyenMaiMouseClicked
        // TODO add your handling code here:
        ArrayList<KhuyenMai> km = qlkm.getAllKM();
        int i = tblBangKhuyenMai.getSelectedRow();
        setFormKhuyenMai(km.get(i));

    }//GEN-LAST:event_tblBangKhuyenMaiMouseClicked

    private void btXoaKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btXoaKMMouseClicked
        // TODO add your handling code here:
        int i = tblBangKhuyenMai.getSelectedRow();
        String ma = (String) tblBangKhuyenMai.getValueAt(i, 1);
        Boolean xoa = qlkm.xoaMaKM(ma);
        if (xoa) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            loadBangKhuyeMai();
        }
    }//GEN-LAST:event_btXoaKMMouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        String tk = txtTimKiemHDCT.getText();
        defau = (DefaultTableModel) tblBangoHDCT.getModel();
        defau.setRowCount(0);
        int stt = 0;
        for (HoaDon h : qlhd.searchHD(tk)) {
            stt++;
            if (h.getTrangThai().equals("Da thanh toan") || h.getTrangThai().equals("Huy hoa don")) {
                defau.addRow(new Object[]{
                    stt, h.getMaHD(), h.getTenNV(), h.getNgay(), h.getTrangThai()
                });
            }
            rdTatCa.setSelected(true);
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void tblGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGioHangMouseClicked
        // TODO add your handling code here:
        int a = (int) tblGioHang.getSelectedRow();
        String i = JOptionPane.showInputDialog("Thay đổi số lượng");
        if (i == null) {
            return;
        }
        int sl = (int) tblGioHang.getValueAt(a, 3);
        String ma = (String) tblGioHang.getValueAt(a, 1);
        int td = sl - Integer.parseInt(i);
        Boolean c = qlsp.congSP(td, ma);
        if (c) {
            loadBangSanPham();
        }
        Boolean tru = qlsp.truiSPtrogMa(Integer.parseInt(i), ma);
        if (tru) {
            loadGioHang();
        }
        int tong = 0;
        for (GioHang gioHang : qlgh.getGioHang(txtMa.getText())) {
            tong += gioHang.thanhTien();
        }
        txtTongTien.setText(tong + "");
    }//GEN-LAST:event_tblGioHangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHangView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BanHangView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ChatLieu;
    private javax.swing.JTextField DonGia;
    private javax.swing.JTextField Ma;
    private javax.swing.JTextField Ten;
    private javax.swing.JButton btApDung;
    private javax.swing.JButton btCapNhat;
    private javax.swing.JButton btHuyHoaDon;
    private javax.swing.JButton btTaoHoaDon;
    private javax.swing.JButton btThemKM;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btTimKiemKM;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton btXoaKM;
    private javax.swing.JButton bthem;
    private javax.swing.JButton btttTimSP;
    private javax.swing.JButton btttXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboSize;
    private javax.swing.JComboBox<String> cboTheLoai;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JRadioButton rdDa;
    private javax.swing.JRadioButton rdHuy;
    private javax.swing.JRadioButton rdTatCa;
    private javax.swing.JTextField soLuong;
    private javax.swing.JTable tblBangGioHangoHDCT;
    private javax.swing.JTable tblBangKhuyenMai;
    private javax.swing.JTable tblBangoHDCT;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblQLSP;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtDKKM;
    private javax.swing.JTextField txtGiam;
    private javax.swing.JTextField txtKMBanHang;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JTextField txtNgayBD;
    private javax.swing.JTextField txtNgayKT;
    private javax.swing.JTextField txtSoLuongKM;
    private javax.swing.JTextField txtTK;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenKM;
    private javax.swing.JTextField txtTienKhach;
    private javax.swing.JTextField txtTienThua;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTimKiemHDCT;
    private javax.swing.JTextField txtTimKiemKM;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtVaiTroKM;
    // End of variables declaration//GEN-END:variables
}
